services:
  grafana:
    image: ghcr.io/volkovlabs/app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-rss-datasource,marcusolsson-static-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-text-panel
      - ./static/provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-rss-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-text-panel
      - ./static/provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=volkovlabs-rss-datasource,marcusolsson-static-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-text-panel
      - ./static/provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/home/pwuser/test
      - ./dist:/home/pwuser/dist
    profiles:
      - e2e
